// PulseUnit — Pathologies par système avec définitions.
// Champ rea:true = pathologie fréquente / prioritaire en réanimation.
// Expose window.PATHOLOGIES_DATA

window.PATHOLOGIES_DATA = [

  /* ===== CARDIOLOGIE ===== */
  { sys:"Cardiologie", rea:true,  id:"fa",           name:"Fibrillation auriculaire (FA)",          def:"Arythmie supra-ventriculaire caractérisée par une dépolarisation anarchique des oreillettes (400–600/min) donnant un rythme ventriculaire irrégulier. Risque principal : AVC embolique (score CHA₂DS₂-VASc). Traitement : anticoagulation, contrôle du rythme (amiodarone, choc électrique) ou de la fréquence (bêtabloquants, digoxine)." },
  { sys:"Cardiologie", rea:true,  id:"idam",          name:"Infarctus du myocarde (IDM)",            def:"Nécrose ischémique par occlusion coronaire. STEMI : sus-décalage ST persistant → revascularisation < 90 min (coronarographie). NSTEMI : sans sus-décalage, enzymes élevées. Complications : choc cardiogénique, FV, IM aiguë, péricardite post-IDM. Traitement : double antiagrégation, anticoagulation, revascularisation." },
  { sys:"Cardiologie", rea:true,  id:"ic",            name:"Insuffisance cardiaque aiguë (ICA)",     def:"Décompensation brutale de la fonction cardiaque. IC gauche : dyspnée, OAP, crépitants. IC droite : œdèmes, TJ, hépatomégalie. Choc cardiogénique : ICA + hypoperfusion. Traitement : O2/VNI, diurétiques IV, vasodilatateurs, amines si choc, assistance circulatoire (ECMO-VA, Impella)." },
  { sys:"Cardiologie", rea:true,  id:"oap",           name:"Œdème aigu pulmonaire (OAP)",            def:"Inondation alvéolaire par élévation brutale de la pression capillaire (cardiogénique) ou lésion endothéliale (SDRA). Orthopnée, expectoration mousseuse rosée, désaturation rapide. Traitement : position assise, O2 haut débit ou VNI (CPAP), furosémide IV, dérivés nitrés si PA > 100." },
  { sys:"Cardiologie", rea:true,  id:"choc_card",     name:"Choc cardiogénique",                     def:"Défaillance de pompe primitive : PAS < 90 mmHg malgré remplissage adéquat, IC < 2,2 L/min/m², PAPO > 18 mmHg. Cause principale : IDM massif (VG). Traitement : noradrénaline + dobutamine, coronarographie urgente, assistance circulatoire (ECMO-VA, IABP, Impella), discussion TAVI si RA serré décompensé." },
  { sys:"Cardiologie", rea:true,  id:"tampon",        name:"Tamponnade cardiaque",                   def:"Compression des cavités cardiaques par épanchement péricardique sous tension. Triade de Beck : hypotension + turgescence jugulaire + assourdissement des bruits. Pulsus paradoxus. Echo : collapsus des cavités droites. Urgence : péricardiocentèse guidée écho ou drainage chirurgical." },
  { sys:"Cardiologie", rea:true,  id:"disseaorte",    name:"Dissection aortique",                    def:"Déchirure de l'intima créant un faux chenal. Type A (crosse et aorte ascendante) : urgence chirurgicale absolue. Type B (aorte descendante) : traitement médical sauf complications (ischémie viscérale, expansion). Douleur en coup de poignard irradiant dans le dos. Contrôle PA strict (Nicardipine IV)." },
  { sys:"Cardiologie", rea:true,  id:"ep",            name:"Embolie pulmonaire grave (EP)",           def:"Obstruction artérielle pulmonaire par thrombus. EP massive : choc ou hypotension → thrombolyse systémique (Alteplase 100 mg IV) ou embolectomie. EP submassive : dysfonction VD sans choc → anticoagulation + surveillance. EP faible risque : anticoagulation orale (AOD). PESI pour stratification." },
  { sys:"Cardiologie", rea:false, id:"tvp",           name:"Thrombose veineuse profonde (TVP)",       def:"Thrombus dans le réseau veineux profond, souvent membres inférieurs. Triade de Virchow : stase, hypercoagulabilité, lésion endothéliale. Complication principale : EP. Traitement : HBPM puis AOD ou AVK 3–6 mois. Filtre cave si contre-indication aux anticoagulants." },
  { sys:"Cardiologie", rea:true,  id:"tach_vent",     name:"Tachycardie ventriculaire (TV)",          def:"Arythmie ventriculaire FC > 100/min, complexes larges. TV soutenue (> 30 s) : risque hémodynamique élevé. TV polymorphe (torsade de pointes) : QT long, hypokaliémie. Traitement : CEE si instabilité, amiodarone IV si stable, correction des troubles ioniques. TV récidivante : DAI, ablation." },
  { sys:"Cardiologie", rea:true,  id:"fv",            name:"Fibrillation ventriculaire (FV)",         def:"Dépolarisation ventriculaire anarchique → arrêt circulatoire immédiat. Principale cause d'ACR. Traitement : RCP immédiate, choc électrique 200 J biphasique dès disponibilité, adrénaline 1 mg/3 min, amiodarone 300 mg après 3 chocs. Identifier et corriger la cause." },
  { sys:"Cardiologie", rea:true,  id:"bav3",          name:"Bloc auriculo-ventriculaire III (BAV 3)", def:"Dissociation complète auriculaire/ventriculaire. Rythme ventriculaire d'échappement lent (20–40/min). Risque : syncope, ACR (asystolie). Causes : IDM inférieur, Lyme, médicaments. Traitement immédiat : atropine ou isoprénaline IV. Traitement définitif : pace-maker cardiaque." },
  { sys:"Cardiologie", rea:false, id:"pericardite",   name:"Péricardite aiguë",                      def:"Inflammation du péricarde. Douleur thoracique augmentée au décubitus, frottement péricardique, sus-décalage ST diffus concave en selle. Causes : virale (Coxsackie), bactérienne, post-IDM (Dressler), auto-immune. Traitement : AINS + colchicine 3 mois. Restriction d'activité physique." },
  { sys:"Cardiologie", rea:true,  id:"myocardite",    name:"Myocardite aiguë",                       def:"Inflammation du myocarde, souvent virale (parvovirus B19, Coxsackie). Tableau : douleur thoracique, troubles du rythme, IC aiguë, choc. Biomarqueurs élevés (troponine). IRM : rehaussement tardif de gadolinium. Traitement symptomatique, immunosuppresseurs si fulminante, ECMO-VA si choc." },
  { sys:"Cardiologie", rea:false, id:"rao",           name:"Rétrécissement aortique serré (RA)",      def:"Sténose valvulaire aortique < 1 cm². Triade de Heberden : angor, syncope, insuffisance cardiaque. Gradient moyen > 40 mmHg. Étiologie dégénérative (calcification) chez le sujet âgé. Traitement : TAVI (voie percutanée) ou remplacement valvulaire chirurgical. Pas de diurétiques agressifs." },
  { sys:"Cardiologie", rea:false, id:"im",            name:"Insuffisance mitrale (IM)",               def:"Régurgitation du VG vers l'OG en systole. Aiguë : rupture de cordage ou pilier (IDM) → choc ou OAP fulminant. Chronique : souffle holosystolique, dilatation OG et VG. Traitement : remplacement ou plastie mitrale, MitraClip (voie percutanée). IM aiguë = urgence chirurgicale." },
  { sys:"Cardiologie", rea:false, id:"cardio_rythm",  name:"Flutter auriculaire",                    def:"Macroréentrée auriculaire typique, fréquence auriculaire 250–350/min avec bloc 2:1 donnant FC ~ 150/min. ECG : ondes F en dents de scie en D2D3VF. Risque embolique identique à la FA. Traitement : anticoagulation, cardioversion, ablation par radiofréquence (isthme cavo-tricuspide) taux succès > 95 %." },

  /* ===== PNEUMOLOGIE / RESPIRATOIRE ===== */
  { sys:"Pneumologie / Respiratoire", rea:true,  id:"sdra",          name:"Syndrome de détresse respiratoire aiguë (SDRA)", def:"Lésions alvéolaires diffuses non cardiogéniques. Critères Berlin : début < 1 sem, infiltrats bilatéraux, P/F < 300. Sévérité : léger (200–300), modéré (100–200), sévère (< 100). Ventilation protectrice : VT 6 mL/kg IBW, Pplat ≤ 30 cmH₂O, PEEP titrée. Décubitus ventral ≥ 16 h/j si P/F < 150. Curarisation 48 h si sévère." },
  { sys:"Pneumologie / Respiratoire", rea:true,  id:"bpco",          name:"BPCO décompensée",                               def:"Exacerbation aiguë de la BPCO. Aggravation dyspnée, expectorations purulentes, hypoxémie ± hypercapnie. Gaz du sang : pH < 7,35 + pCO2 > 45 mmHg = insuffisance respiratoire aiguë hypercapnique. VNI (BPAP) si pH 7,25–7,35. Intubation si pH < 7,25 ou échec VNI. Bronchodilatateurs, corticoïdes IV 40 mg/j, antibiotiques." },
  { sys:"Pneumologie / Respiratoire", rea:true,  id:"asthme_grave",  name:"Asthme aigu grave (AAG)",                        def:"Bronchospasme sévère réfractaire. Critères : SpO2 < 92 %, DEP < 50 %, silence auscultatoire, tirage majeur, cyanose. β2 nébulisés répétés, ipratropium, méthylprednisolone 1 mg/kg IV, sulfate de magnésium 2 g IV. Ventilation invasive difficile (piège gazeux, barotraumatisme) : sédation profonde, basse fréquence, haut VT prudent." },
  { sys:"Pneumologie / Respiratoire", rea:true,  id:"pneumo_infec",  name:"Pneumonie infectieuse sévère",                   def:"Infection parenchymateuse pulmonaire grave (score PSI IV-V ou CURB-65 ≥ 3). Communautaire : pneumocoque, Légionelle (doit être couverte si forme grave), atypiques. Nosocomiale : Pseudomonas, SARM, Klebsiella. Traitement : C3G + macrolide (ou FQ) en communautaire, pipéracilline-tazobactam ou carbapénème + aminoside si nosocomiale grave." },
  { sys:"Pneumologie / Respiratoire", rea:true,  id:"pneumo_asp",    name:"Pneumonie d'aspiration",                         def:"Inhalation de contenu gastrique ou de sécrétions oropharyngées. Facteurs de risque : troubles déglutition, conscience, décubitus prolongé. Localisation préférentielle : segment postérieur LSD ou LID. Antibiothérapie : amoxicilline-acide clavulanique ou C3G + métronidazole. Prévention : position semi-assise 30°, soins de bouche." },
  { sys:"Pneumologie / Respiratoire", rea:true,  id:"pavm",          name:"Pneumonie associée à la VM (PAVM)",              def:"Pneumonie survenant ≥ 48 h après intubation. Principale infection nosocomiale en réanimation. Germes : Pseudomonas, Acinetobacter, SARM. Diagnostic : critères cliniques (fièvre, sécrétions purulentes, consolidation) + LBA (≥ 10⁴ UFC/mL). Traitement probabiliste puis adapté à l'antibiogramme. Durée 7–8 j si réponse favorable." },
  { sys:"Pneumologie / Respiratoire", rea:true,  id:"pneumo_thorax", name:"Pneumothorax compressif",                        def:"Air sous tension dans la plèvre comprimant le médiastin → collapsus cardiovasculaire imminent. Déviation trachéale, distension jugulaire, silence auscultatoire unilatéral, désaturation, choc. Décompression en urgence à l'aiguille (2e EIC ligne médioclaviculaire) sans attendre imagerie, puis drainage pleural." },
  { sys:"Pneumologie / Respiratoire", rea:true,  id:"hemothorax",    name:"Hémothorax",                                     def:"Épanchement sanguin pleural. Causes : trauma thoracique (principale), rupture d'anévrisme, trouble de coagulation. Hémothorax massif : > 1500 mL ou > 200 mL/h. Traitement : drainage pleural, remplissage, transfusion, chirurgie si persistant. Risque d'empyème si non drainé." },
  { sys:"Pneumologie / Respiratoire", rea:false, id:"pleuresie",     name:"Pleurésie",                                      def:"Épanchement liquidien dans la cavité pleurale. Transsudat (IC, cirrhose, syndrome néphrotique) ou exsudat (infectieux, néoplasique, EP). Critères de Light pour différencier. Diagnostic : ponction pleurale. Traitement de la cause ± drainage si volumineux ou infecté (empyème → décortication)." },
  { sys:"Pneumologie / Respiratoire", rea:false, id:"htap",          name:"Hypertension artérielle pulmonaire (HTAP)",      def:"PAP moyenne > 25 mmHg au repos. Idiopathique, secondaire (cardiopathie gauche, BPCO, TEP chronique). Symptômes : dyspnée d'effort, syncope, IC droite. Traitement : inhibiteurs de la PDE-5 (sildénafil), analogues de la prostacycline, antagonistes de l'endothéline. Transplantation pulmonaire au stade terminal." },
  { sys:"Pneumologie / Respiratoire", rea:false, id:"fibrose_pulm",  name:"Fibrose pulmonaire idiopathique (FPI)",          def:"Fibrose interstitielle progressive de cause inconnue. Crepitants 'velcro', hippocratisme digital, pattern UIP (rayon de miel) en TDM. EFR : trouble ventilatoire restrictif. Traitement : pirfénidone ou nintédanib pour ralentir la progression. Transplantation pulmonaire si critères." },

  /* ===== NEUROLOGIE / NEUROCHIRURGIE ===== */
  { sys:"Neurologie / Neurochirurgie", rea:true,  id:"avc_isch",    name:"AVC ischémique",                        def:"Occlusion artérielle cérébrale → nécrose. Thrombolyse IV (Alteplase) si < 4h30, sans contre-indication. Thrombectomie mécanique si occlusion gros tronc (ACM, ACI, tronc basilaire) jusqu'à 24 h en cas de mismatch imaging. NIHSS pour évaluation. Unité neurovasculaire obligatoire. Antiplaquettaires en prévention secondaire (ou anticoagulants si FA)." },
  { sys:"Neurologie / Neurochirurgie", rea:true,  id:"avc_hem",     name:"AVC hémorragique",                      def:"Rupture vasculaire intraparenchymateuse. Causes : HTA (principale), MAV, angiopathie amyloïde, anticoagulants. Pas de thrombolyse. Traitement : contrôle tensionnel (PAS cible < 140 mmHg), reversal anticoagulants, neurochirurgie si hématome volumineux/cérébelleux, DCP si hydrocéphalie." },
  { sys:"Neurologie / Neurochirurgie", rea:true,  id:"hsa",         name:"Hémorragie sous-arachnoïdienne (HSA)", def:"Rupture d'anévrisme dans l'espace sous-arachnoïdien. Céphalée foudroyante ('thunderclap'). Score de Hunt & Hess pour la gravité. Complications : vasospasme (J4–J14), resaignement, hydrocéphalie. Traitement : exclusion anévrismale (neurochirurgie ou coiling endovasculaire), nimodipine IV, surveillance PIC en réa si grade élevé." },
  { sys:"Neurologie / Neurochirurgie", rea:true,  id:"htc",         name:"Hypertension intracrânienne (HTIC)",    def:"PIC > 20 mmHg. Causes : TC, AVC, HSA, hydrocéphalie, tumeur, méningite. Triade de Cushing : HTA + bradycardie + bradypnée = engagement imminent. Traitement : tête à 30°, éviter hypercapnie, osmothérapie (mannitol 20 % ou SSH 7,5 %), curarisation, barbiturates, décompression chirurgicale. Objectif PPC > 60 mmHg." },
  { sys:"Neurologie / Neurochirurgie", rea:true,  id:"tc",          name:"Traumatisme crânien grave (TCG)",       def:"GCS ≤ 8 après normalisation hémodynamique. Mécanismes : DAD, contusions, hématomes. Scanner : Marshall classification. Objectifs réanimation : PPC > 60 mmHg, PIC < 20 mmHg, PaO2 > 80, normocapnie (PaCO2 35–45), normothermie, normoglycémie, PA syst > 110 mmHg. Hypocapnie de sauvetage si engagement." },
  { sys:"Neurologie / Neurochirurgie", rea:true,  id:"etat_epi",    name:"État de mal épileptique (EME)",         def:"Crise épileptique ≥ 5 min ou crises répétées sans reprise de conscience. EME convulsif généralisé = urgence vitale. Protocole : BZD IV (clonazépam 1 mg ou diazépam 10 mg) → 2e ligne (valproate 30 mg/kg, lévétiracétam 60 mg/kg ou fosphénytoïne) → anesthésie générale si réfractaire (midazolam, propofol, thiopental). EEG monitoring." },
  { sys:"Neurologie / Neurochirurgie", rea:true,  id:"hsd",         name:"Hématome sous-dural (HSD) aigu",       def:"Collection hématique entre dure-mère et arachnoïde, souvent traumatique. Intervalle libre trompeur puis dégradation rapide. Scanner : image en croissant hyperdense. Urgence chirurgicale si GCS ≤ 8, hématome > 10 mm ou midline shift > 5 mm. Pronostic sévère si déficit neurologique précoce." },
  { sys:"Neurologie / Neurochirurgie", rea:true,  id:"hed",         name:"Hématome extradural (HED)",             def:"Collection entre dure-mère et crâne, souvent par rupture de l'artère méningée moyenne (fracture temporale). Intervalle libre classique. Scanner : image lenticulaire hyperdense. Urgence chirurgicale absolue si volume > 30 mL ou GCS ≤ 8. Excellent pronostic si traitement précoce." },
  { sys:"Neurologie / Neurochirurgie", rea:true,  id:"mort_cerveau", name:"Mort encéphalique (ME)",               def:"Destruction totale et irréversible du cerveau incluant le tronc cérébral. Conditions : cause connue, absence de facteurs confondants (hypothermie < 35°C, médicaments sédatifs, hypotension). Critères cliniques : absence de conscience, réflexes du tronc, apnée. Confirmation : 2 EEG isoélectriques ou angioscanner cérébral. Protocole donneur d'organes." },
  { sys:"Neurologie / Neurochirurgie", rea:false, id:"sep",         name:"Sclérose en plaques (SEP)",             def:"Maladie auto-immune démyélinisante du SNC. Formes : récurrente-rémittente (85 %), secondairement progressive, primaire progressive. Poussées : optic neuritis, syndrome pyramidal, cérébelleux, sensitif. Traitement de poussée : méthylprednisolone 1 g/j × 3 j. Traitements de fond : interférons, natalizumab, ocrélizumab." },
  { sys:"Neurologie / Neurochirurgie", rea:false, id:"parkinson",   name:"Maladie de Parkinson",                  def:"Dégénérescence des neurones dopaminergiques de la substance noire. Triade : tremblements de repos, rigidité, akinésie. Traitement : lévodopa + carbidopa (gold standard), agonistes dopaminergiques, IMAO-B. Complications motrices : fluctuations, dyskinésies. DBS (stimulation cérébrale profonde) au stade avancé." },
  { sys:"Neurologie / Neurochirurgie", rea:false, id:"myasthenie",  name:"Myasthénie grave",                      def:"Maladie neuromusculaire auto-immune (anticorps anti-récepteurs AChR). Faiblesse fluctuante, ptôsis, diplopie, dysphonie. Crise myasthénique : détresse respiratoire → intubation. Diagnostics : EMG, dosage anticorps. Traitement : pyridostigmine, corticoïdes, azathioprine, échanges plasmatiques ou IgIV en crise." },
  { sys:"Neurologie / Neurochirurgie", rea:false, id:"gbs",         name:"Syndrome de Guillain-Barré (SGB)",      def:"Polyradiculonévrite aiguë inflammatoire post-infectieuse. Déficit moteur ascendant, aréflexie, LCR dissocie albumino-cytologique. Complications : insuffisance respiratoire (intubation dans 25 %), dysautonomie. Traitement : IgIV 0,4 g/kg/j × 5 j ou échanges plasmatiques × 6. Pas de corticoïdes." },

  /* ===== INFECTIOLOGIE / SEPSIS ===== */
  { sys:"Infectiologie / Sepsis", rea:true,  id:"sepsis",      name:"Sepsis",                                    def:"Dysrégulation de la réponse de l'hôte à une infection → défaillance d'organe (SOFA ≥ 2). qSOFA (alerte) : FR ≥ 22, GCS < 15, PAS ≤ 100. Traitement : antibiotiques dans l'heure après prélèvements (hémocultures), remplissage 30 mL/kg si hypoperfusion, réévaluation clinique et biologique." },
  { sys:"Infectiologie / Sepsis", rea:true,  id:"choc_sep",    name:"Choc septique",                             def:"Sepsis + vasoplégie réfractaire au remplissage nécessitant vasopresseurs pour PAM ≥ 65 mmHg + lactate > 2 mmol/L. Mortalité > 40 %. Noradrénaline en 1re intention (0,1–1 µg/kg/min). Vasopressine en 2e ligne. Dobutamine si dysfonction cardiaque associée. Hydrocortisone 200 mg/j si choc réfractaire. Bundle Sepsis-3." },
  { sys:"Infectiologie / Sepsis", rea:true,  id:"meningite",   name:"Méningite bactérienne",                     def:"Infection méningée purulente. Triade : fièvre + céphalée + raideur nucale. Purpura fulminans (méningocoque) = urgence vitale, antibiotiques immédiats (C3G). PL si pas de signe focal (fond d'œil ou TDM si doute). Céphalosporine 3e génération + dexaméthasone 10 mg/6 h × 4 j. Listériose : ajouter amoxicilline chez > 50 ans ou immunodéprimé." },
  { sys:"Infectiologie / Sepsis", rea:true,  id:"endocardite", name:"Endocardite infectieuse",                    def:"Infection de l'endocarde valvulaire. Critères de Duke. Germes : streptocoque oral (communautaire), staphylocoque (IV, prothèse), entérocoque. Complications : emboles septiques, insuffisance valvulaire aiguë, abcès annulaire. Antibiothérapie bactéricide prolongée (4–6 sem). Chirurgie si complication hémodynamique, abcès, végétation volumineuse." },
  { sys:"Infectiologie / Sepsis", rea:true,  id:"fasciite",    name:"Fasciite nécrosante",                        def:"Infection nécrosante des fascias, extension rapide. Type 1 (polymicrobienne, terrain fragilisé) ou type 2 (streptocoque A, terrain sain). Douleur intense disproportionnée, érythème puis nécrose cutanée, crépitation gazeuse, choc. Urgence chirurgicale : parage agressif répété. Antibiothérapie : pipéracilline-tazobactam + clindamycine + aminoside ± IVIG." },
  { sys:"Infectiologie / Sepsis", rea:true,  id:"iatc",        name:"Infection sur cathéter (ILC)",               def:"Bactériémie liée à un cathéter veineux central. Germes : SCN (CVC), S. aureus (voie périphérique). Critères : hémocultures positives, pas d'autre foyer, réponse à l'ablation du KT. Traitement : ablation du cathéter ± vancomycine selon gravité. Durée 14 j si S. aureus, EI exclue. Prévention : asepsie maximale pose et manipulation." },
  { sys:"Infectiologie / Sepsis", rea:false, id:"tuberculose", name:"Tuberculose pulmonaire",                     def:"Infection à Mycobacterium tuberculosis. Primo-infection le plus souvent asymptomatique. TB pulmonaire active : toux > 3 sem, hémoptysie, sueurs nocturnes, amaigrissement. Diagnostic : ECBC × 3, quantiféron, IDR, TDM thoracique. Traitement : quadrithérapie (RIPE) 2 mois + bithérapie (RI) 4 mois. Isolement aérien." },
  { sys:"Infectiologie / Sepsis", rea:false, id:"paludisme",   name:"Paludisme grave (Plasmodium falciparum)",    def:"Urgence médicale. Critères OMS de gravité : parasite ≥ 5 %, coma (neurosévère), anémie sévère, OAP, IRA, hypoglycémie, acidose. Traitement : artésunate IV (> quinine). Bilan : NFS, parasitémie, glycémie, LDH, TP, créatinine. Dihydroartémisinine-pipéraquine per os si forme non grave." },
  { sys:"Infectiologie / Sepsis", rea:true,  id:"covid",       name:"COVID-19 grave",                             def:"Infection SARS-CoV-2 avec détresse respiratoire. Critères gravité : SpO2 < 90 %, FR > 30/min, infiltrats > 50 %. Traitement : dexaméthasone 6 mg/j × 10 j, anticoagulation (HBPMc préventif ou thérapeutique selon score), antiviraux (nirmatrelvir/ritonavir) si précoce. VM protectrice si SDRA. Décubitus ventral si P/F < 150." },
  { sys:"Infectiologie / Sepsis", rea:true,  id:"aspergillose",name:"Aspergillose invasive (AI)",                def:"Infection fongique grave chez l'immunodéprimé (neutropénie, corticothérapie, BPCO, COVID sévère). Galactomannane sérique ou LBA, TDM (signe du halo). Traitement : voriconazole IV (1re ligne) ou isavuconazole. Alternative : amphotéricine B liposomale. Durée : au moins 6–12 semaines selon immunosuppression." },
  { sys:"Infectiologie / Sepsis", rea:false, id:"vih",         name:"VIH — SIDA",                                def:"Infection par le VIH → dépletion CD4, immunodépression profonde (SIDA si CD4 < 200/mm³). Infections opportunistes : pneumocystose (PCP), toxoplasmose, CMV, cryptocoque, MAC. Traitement antirétroviral (ARV) : trithérapie à vie. Prophylaxies si CD4 < 200. Dépistage universel recommandé." },

  /* ===== HÉPATO-GASTRO-ENTÉROLOGIE ===== */
  { sys:"Hépato-gastro-entérologie", rea:true,  id:"pancreatite",  name:"Pancréatite aiguë sévère",               def:"Scores de Ranson ≥ 3 ou CTSI ≥ 7 (Balthazar) = forme sévère. Nécrose pancréatique infectée = indication de nécrosectomie endoscopique ou chirurgicale. Traitement : remplissage intensif (Ringer lactate), nutrition entérale précoce (sonde nasojéjunale), antalgie, pas d'antibioprophylaxie. Sepsis + nécrose → carbapénème." },
  { sys:"Hépato-gastro-entérologie", rea:true,  id:"iha",          name:"Insuffisance hépatique aiguë (IHA)",     def:"Défaillance hépatique brutale sans hépatopathie connue. TP < 50 % + encéphalopathie < 26 sem. Causes : paracétamol (NAC IV), hépatite virale fulminante, toxique, Budd-Chiari. Critères King's College pour transplantation. Surveillance : PIC (si encéphalopathie IV), glycémie, TP/INR, créatinine, pression artérielle." },
  { sys:"Hépato-gastro-entérologie", rea:true,  id:"hd_hte",       name:"Hémorragie digestive haute (HDH)",       def:"Saignement au-dessus de l'angle de Treitz. Hématémèse ou méléna. Causes : UGD (principale), varices œsophagiennes (cirrhose), Mallory-Weiss. Score de Blatchford pour la gravité. Endoscopie < 12 h si instable, < 24 h sinon. IPP IV, octréotide (varices). TIPS si varices non contrôlées." },
  { sys:"Hépato-gastro-entérologie", rea:true,  id:"perit",        name:"Péritonite",                              def:"Infection du péritoine. Primaire (IPA sur cirrhose : PNN > 250/mm³ dans ascite, cefotaxime IV). Secondaire (perforation digestive) : urgence chirurgicale, laparotomie d'hémostase et lavage. Tertiaire (échec traitement) : fongique souvent. Antibiothérapie : pipéracilline-tazobactam ± candine si risque fungique." },
  { sys:"Hépato-gastro-entérologie", rea:true,  id:"cirrho_deco",  name:"Cirrhose décompensée",                   def:"Décompensation : ascite (1re cause), hémorragie digestive, encéphalopathie hépatique (NH4+ > 50 µmol/L, EEG), infection, syndrome hépatorénal. Score Child-Pugh / MELD. SHR type 1 (IRA) : terlipressine + albumine. Encéphalopathie : lactitol, rifaximine. Transplantation hépatique si MELD > 15." },
  { sys:"Hépato-gastro-entérologie", rea:false, id:"crohn",        name:"Maladie de Crohn",                       def:"MICI transmurale touchant tout le tube digestif. Localisation : iléon terminal (principale). Complications : sténose, fistule, abcès, cancer. Traitement : corticoïdes (poussée), immunosuppresseurs (azathioprine), biothérapies (anti-TNF, ustekinumab, védolizumab). Chirurgie si complication." },
  { sys:"Hépato-gastro-entérologie", rea:false, id:"rch",          name:"Rectocolite hémorragique (RCH)",          def:"MICI limitée à la muqueuse colo-rectale (muqueux), évolution par poussées. Rectorragies, diarrhées glairosanglantes. Mégacôlon toxique (complication grave) : colectomie urgente. Traitement : aminosalicylés, corticoïdes (poussée), anti-TNF (infliximab), védo-/ustékinumab, colectomie totale si résistance." },
  { sys:"Hépato-gastro-entérologie", rea:false, id:"ulcere",       name:"Ulcère gastroduodénal (UGD)",             def:"Ulcération gastrique ou duodénale par déséquilibre facteurs agressifs/protecteurs. Causes : H. pylori (principale), AINS, tabac, stress. Complication : hémorragie, perforation, sténose. Traitement : IPP + trithérapie anti-Hp. AINS : éviter ou protection IPP. Perforation = urgence chirurgicale." },
  { sys:"Hépato-gastro-entérologie", rea:false, id:"occlusion",    name:"Occlusion intestinale aiguë",             def:"Arrêt du transit par obstacle mécanique (bride, volvulus, cancer) ou fonctionnel (iléus). Vomissements, distension abdominale, arrêt des matières et gaz. ASP/TDM pour le diagnostic et la cause. Traitement : SNG aspiration, remplissage. Chirurgie si nécrose, ischémie ou échec traitement médical." },

  /* ===== NÉPHROLOGIE ===== */
  { sys:"Néphrologie", rea:true,  id:"ira",     name:"Insuffisance rénale aiguë (IRA)",          def:"Élévation brutale de la créatinine ou oligoanurie. Classification KDIGO : stade 1 (créat ×1,5), stade 2 (×2), stade 3 (×3 ou > 354 µmol/L ou anurie). Causes : fonctionnelle (hypovolémie → remplissage), organique (NTA, GN, vasculaire), obstructive (sondage vésical). Traitement étiologique + EER si stade 3 symptomatique." },
  { sys:"Néphrologie", rea:true,  id:"eer",      name:"Épuration extra-rénale (EER)",             def:"Suppléance rénale. CVVHF/CVVHDF (hémofiltration continue) : préférée en réanimation (meilleure tolérance hémodynamique). Hémodialyse intermittente : si patient stable. Indications EER : hyperhydratation réfractaire, K+ > 6,5 mEq/L, pH < 7,15, urémie symptomatique, toxique dialysable. Anticoagulation : héparine ou citrate (CVVHDF)." },
  { sys:"Néphrologie", rea:true,  id:"hyperk",   name:"Hyperkaliémie sévère",                     def:"K+ > 6,5 mEq/L ou signes ECG (ondes T pointues, élargissement QRS, BAV, FV). Urgence cardiologique. Traitement : 1) gluconate de calcium IV (protection membranaire immédiate), 2) glucose-insuline IV (transfert K+ intracellulaire), 3) bicarbonate si acidose, 4) résines, 5) EER si réfractaire. Éviter tout apport potassique." },
  { sys:"Néphrologie", rea:true,  id:"hyponat",  name:"Hyponatrémie sévère",                      def:"Na+ < 125 mEq/L ou symptômes neurologiques (céphalées, convulsions, coma). Causes : SIADH, potomanie, pertes sodées. Correction prudente : max +10 mEq/L/24 h (risque myélinolyse centropontine si correction trop rapide). SSH 3 % si convulsions (100 mL IV). Restriction hydrique si SIADH." },
  { sys:"Néphrologie", rea:false, id:"irc",      name:"Insuffisance rénale chronique (IRC)",      def:"DFG < 60 mL/min/1,73 m² persistant > 3 mois. Stades 1–5 (stade 5 : DFG < 15 = IRT). Causes : diabète, HTA, GN chronique. Complications : anémie (EPO), acidose, hyperparathyroïdie secondaire, hyperkaliémie. Traitement conservateur + préparation à la dialyse (HD ou DP) ou transplantation rénale." },
  { sys:"Néphrologie", rea:false, id:"shr",      name:"Syndrome hépatorénal (SHR)",               def:"IRA fonctionnelle grave sur cirrhose décompensée sans autre cause. SHR type 1 : rapide, pronostic fatal sans traitement. SHR type 2 : plus lent, ascite réfractaire. Traitement : terlipressine 0,5–1 mg/4 h + albumine 20 g/j. Transplantation hépatique = traitement définitif." },

  /* ===== ENDOCRINOLOGIE / MÉTABOLISME ===== */
  { sys:"Endocrinologie / Métabolisme", rea:true,  id:"acd",         name:"Acidocétose diabétique (ACD)",          def:"pH < 7,3 + bicarbonates < 15 + glycémie > 14 mmol/L + corps cétoniques. DT1 principalement. Facteur déclenchant : infection, oubli insuline. Traitement : NaCl 0,9 % 1 L/h les 2 premières heures, insuline IVSE (0,1 UI/kg/h), substitution K+ dès que K+ < 5 mEq/L, surveillance horaire glycémie + ionogramme." },
  { sys:"Endocrinologie / Métabolisme", rea:true,  id:"hhnc",        name:"Hyperosmolarité hyperglycémique (HHN)",  def:"Glycémie > 33 mmol/L, osmolalité > 320 mOsm/kg, sans cétoacidose significative. DT2 sujet âgé, souvent lors d'une infection ou déshydratation. Déshydratation massive. Traitement : remplissage progressif (NaCl 0,9 %, 4–6 L/24 h), insuline modérée, anticoagulation, surveillance iono et glycémie/h. Mortalité 20–40 %." },
  { sys:"Endocrinologie / Métabolisme", rea:true,  id:"hypo_gluc",   name:"Hypoglycémie sévère",                   def:"Glycémie < 3 mmol/L avec signes neurologiques ou < 2,5 mmol/L. Causes : insuline (surdosage), sulfamides, alcool, jeûne, insulinome. Traitement IV : G30 % 2–4 ampoules de 10 mL (si voie veineuse), puis G10 % IVSE. IM : glucagon 1 mg (sujets sans IV). Surveiller glycémie toutes les 15 min. Sulfamides : risque de récidive prolongée." },
  { sys:"Endocrinologie / Métabolisme", rea:true,  id:"thyro_crise", name:"Crise thyréotoxique",                   def:"Hyperthyroïdie extrême avec défaillance multiviscérale. Score de Burch-Wartofsky > 45 = crise. Fièvre > 40°C, tachycardie, IC, trouble conscience, ictère. Urgence : propylthiouracile 600 mg puis 200 mg/4 h, solution de Lugol 5–10 gouttes/8 h (après thionamides), propranolol IV, dexaméthasone 2 mg/6 h, réanimation symptomatique." },
  { sys:"Endocrinologie / Métabolisme", rea:true,  id:"insuf_surr",  name:"Insuffisance surrénalienne aiguë",      def:"Crise addissonienne. Hypotension réfractaire, hypoglycémie, hyponatrémie, hyperkaliémie, mélanodermie. Causes : corticothérapie prolongée interrompue, sepsis révélant une insuffisance latente, nécrose surrénalienne (Waterhouse-Friderichsen). Traitement : hydrocortisone 100 mg IV bolus puis 200 mg/24 h IVSE, remplissage, G30 %." },
  { sys:"Endocrinologie / Métabolisme", rea:false, id:"diab_t2",     name:"Diabète de type 2",                     def:"Hyperglycémie chronique par insulinorésistance + carence insulinique relative. HbA1c cible < 7 % (< 8 % si sujet âgé). Complications : micro (rétinopathie, néphropathie, neuropathie) et macroangiopathie (IDM, AVC, AOMI). Traitement : metformine en 1re intention, puis SGLT2-i ou GLP-1-RA selon comorbidités." },
  { sys:"Endocrinologie / Métabolisme", rea:false, id:"hypothyro",   name:"Hypothyroïdie — myxœdème",              def:"Déficit en hormones thyroïdiennes. Causes : thyroïdite de Hashimoto (principale), iatrogène. Asthénie, frilosité, constipation, prise de poids, bradycardie, œdème. Myxœdème coma : urgence, hypothermie, bradycardie, trouble conscience. Traitement : lévothyroxine ± hydrocortisone si suspicion d'insuffisance surrénalienne associée." },
  { sys:"Endocrinologie / Métabolisme", rea:false, id:"hypercalcemie",name:"Hypercalcémie sévère",                 def:"Calcium > 3,5 mmol/L. Causes : hyperparathyroïdie primaire (principale), cancers (métastases osseuses, PTHrP), granulomatoses. Symptômes : nausées, polyurie, confusion, coma, arythmie. Traitement : remplissage NaCl 0,9 % abondant, biphosphonates IV (zolédronate), calcitonine, furosémide après remplissage." },

  /* ===== TRAUMATOLOGIE / CHIRURGIE ===== */
  { sys:"Traumatologie / Chirurgie", rea:true,  id:"poly_trauma",    name:"Polytraumatisme",                       def:"≥ 2 lésions traumatiques graves dont une met en jeu le pronostic vital. Approche ATLS. Triade létale : hypothermie + acidose + CIVD. Damage control surgery : hémostase rapide, remplacement chirurgical différé. Transfusion massive : ratio PFC:CGR 1:1:1. Scanner corps entier (trauma scan) si stable. Objectif : TAM > 50–65 mmHg selon lésions crâniennes associées." },
  { sys:"Traumatologie / Chirurgie", rea:true,  id:"crush",          name:"Syndrome de Crush (rhabdomyolyse)",     def:"Destruction musculaire massive → myoglobinurie, hyperkaliémie, IRA, CID. Causes : compression prolongée, poly-trauma, statines, effort extrême. CPK > 10 000 UI/L. Traitement : remplissage massif (NaCl 0,9 % 1–1,5 L/h), maintien diurèse > 200 mL/h, alcalinisation des urines (bicarbonate), EER si K+ élevé ou anurie." },
  { sys:"Traumatologie / Chirurgie", rea:false, id:"trauma_thor",    name:"Traumatisme thoracique grave",           def:"Contusion pulmonaire, volet thoracique (segments multiples instables), pneumo/hémothorax, contusion myocardique, rupture aortique traumatique. TDM thoracique systématique si mécanisme violent. Volet : antalgie prioritaire, ventilation non invasive ou invasive. Rupture aortique = urgence chirurgicale ou TEVAR." },
  { sys:"Traumatologie / Chirurgie", rea:false, id:"appendicite",    name:"Appendicite aiguë",                     def:"Inflammation de l'appendice iléo-caecal. Douleur migrant vers FID, défense, fièvre modérée, leucocytose. Score d'Alvarado ≥ 7. TDM abdominopelvien pour confirmation. Traitement : appendicectomie cœlioscopique. Antibiothérapie seule discutée si non compliqué. Péritonite appendiculaire = urgence chirurgicale." },
  { sys:"Traumatologie / Chirurgie", rea:false, id:"embol_mes",      name:"Ischémie mésentérique aiguë",           def:"Ischémie intestinale par occlusion artérielle (embolie sur FA, athérosclérose), veineuse ou non occlusive (choc). Douleur abdominale intense, terrain vasculaire. Acidose lactique précoce. Angio-TDM : diagnostic. Traitement : artériographie ± thrombolyse ou embolectomie, résection si nécrose, anticoagulation. Mortalité > 50 % si chirurgie tardive." },

  /* ===== HÉMATOLOGIE / COAGULATION ===== */
  { sys:"Hématologie / Coagulation", rea:true,  id:"cid",          name:"Coagulation intravasculaire disséminée (CIVD)", def:"Activation simultanée de la coagulation et de la fibrinolyse → thromboses microvasculaires + hémorragies. Causes : sepsis (principale), polytraumatisme, cancer, complications obstétricales. Biologie : TP bas, fibrinogène < 1 g/L, D-dimères élevés, thrombopénie. Traitement étiologique + transfusion ciblée (PFC, fibrinogène, plaquettes)." },
  { sys:"Hématologie / Coagulation", rea:true,  id:"tih",          name:"Thrombopénie induite par l'héparine (TIH)", def:"Formation d'anticorps anti-complexes FP4-héparine → thromboses paradoxales + thrombopénie (chute ≥ 50 %). Survient J5–J14 après exposition à l'héparine. Score 4T. Arrêt immédiat et définitif de toute héparine. Relais : danaparoïde, fondaparinux ou argatroban. Pas de transfusion plaquettaire." },
  { sys:"Hématologie / Coagulation", rea:true,  id:"ptt",          name:"Purpura thrombotique thrombocytopénique (PTT)", def:"Micro-angiopathie thrombotique par déficit en ADAMTS13. Pentade : anémie hémolytique, thrombopénie, troubles neurologiques, fièvre, IRA. Urgence médicale : échanges plasmatiques quotidiens + rituximab, corticoïdes. Caplacizumab en 1re ligne. Mortalité > 90 % sans traitement." },
  { sys:"Hématologie / Coagulation", rea:false, id:"anemie_fal",   name:"Anémie falciforme (drépanocytose)",      def:"Hémoglobinopathie par mutation Hb S → falciformation en hypoxie. Crises vaso-occlusives (douleurs osseuses), syndrome thoracique aigu (STA), AVC, priapisme, séquestration splénique. STA : urgence, transfusion d'échange si sévère, O2, bronchodilatateurs. Hydroxyurée en prévention. Transplantation de moelle osseuse curative." },
  { sys:"Hématologie / Coagulation", rea:false, id:"hemophilie",   name:"Hémophilie A et B",                      def:"Déficit en facteur VIII (A) ou IX (B). Hémorragies articulaires (hémarthroses), musculaires, intracrâniennes. Dosage des facteurs (< 1 % = sévère). Traitement : concentrés de facteur (recombinants), émicizumab (prophylaxie hémophilie A). En urgence : facteur recombinant spécifique, FEIBA si inhibiteur." },

  /* ===== OBSTÉTRIQUE ===== */
  { sys:"Obstétrique", rea:true,  id:"eclampsie", name:"Éclampsie",                       def:"Convulsions généralisées chez une prééclamptique. Urgence absolue. Traitement : sulfate de magnésium 4 g IV sur 20 min puis 1–2 g/h (antidote : gluconate de Ca). Antihypertenseurs : nicardipine IV si PAS > 160. Extraction fœtale urgente. Surveillance : réflexes ostéo-tendineux, diurèse, taux de magnésémie." },
  { sys:"Obstétrique", rea:true,  id:"hellp",     name:"Syndrome HELLP",                  def:"Hémolyse + élévation enzymes hépatiques (ASAT/ALAT > 70 UI/L) + thrombopénie (< 100 G/L). Complication sévère de la prééclampsie. Douleur épigastrique / HCD en barre, nausées, hématome sous-capsulaire hépatique. Extraction fœtale en urgence. Corticoïdes (dexaméthasone). Transfusion si nécessaire." },
  { sys:"Obstétrique", rea:true,  id:"hppi",      name:"Hémorragie du post-partum (HPP)", def:"Perte > 500 mL dans les 24 h. Cause principale : atonie utérine. Traitement séquentiel : massage utérin, ocytocine (5–10 UI IV), Sulprostone (500 µg/24 h), remplissage, transfusion si hémodynamique compromise, sondage vésical. Échec : embolisation artérielle ou chirurgie (ligatures, compression, hystérectomie en dernier recours)." },
  { sys:"Obstétrique", rea:false, id:"preeclamp",  name:"Prééclampsie",                    def:"HTA ≥ 140/90 apparaissant après 20 SA + protéinurie ≥ 0,3 g/24 h (ou rapport protéine/créatinine ≥ 30 mg/mmol). Facteurs de risque : primiparité, ATCD familiaux, obésité, DT, grossesse multiple. Aspirin faible dose dès 12 SA si risque élevé. Traitement : antihypertenseurs (nicardipine, méthyldopa), extraction selon terme et sévérité." },

  /* ===== TOXICOLOGIE ===== */
  { sys:"Toxicologie", rea:true,  id:"intox_paracetamol",    name:"Intoxication au paracétamol",               def:"Nécrose hépatocellulaire par saturation des voies de conjugaison (> 150 mg/kg). Nomogramme de Rumack-Matthew pour indication traitement. N-acétylcystéine IV : 150 mg/kg/15 min puis 50 mg/kg/4 h puis 100 mg/kg/16 h. IHF si traitement tardif. Critères King's College pour transplantation hépatique en urgence." },
  { sys:"Toxicologie", rea:true,  id:"intox_benzo",          name:"Intoxication aux benzodiazépines",          def:"Dépression du SNC : sédation, hypotonie, ataxie. Rarement létale seule. Antidote : flumazénil 0,2 mg IV (demi-vie courte, risque de re-sédation, contre-indiqué si épilepsie sous BZD ou dépendance). Traitement symptomatique : protection voies aériennes, O2, surveillance. Lavage gastrique si prise massive récente (< 1 h)." },
  { sys:"Toxicologie", rea:true,  id:"intox_opi",            name:"Intoxication aux opiacés",                  def:"Triade : myosis, dépression respiratoire, coma. FR < 12/min, SaO2 effondrée. Causes : morphine, oxycodone, fentanyl, héroïne. Antidote : naloxone 0,4 mg IV (titration) → 0,04 mg si usage opiacés chronique (risque sevrage). Demi-vie courte (30–90 min) : risque de re-narcotisation, surveiller 6 h minimum." },
  { sys:"Toxicologie", rea:true,  id:"intox_co",             name:"Intoxication au monoxyde de carbone (CO)",  def:"Hypoxie tissulaire par formation de carboxyhémoglobine (HbCO). SpO2 pléthysmographique faussement normale. Bilan : HbCO (co-oxymétrie), troponine, ECG, GCS. Traitement : O2 100 % masque HC 6–12 h (HbCO < 5 %). OHB si HbCO > 25 %, perte de conscience, grossesse, cardiotoxicité. Rechercher d'autres victimes et source." },
  { sys:"Toxicologie", rea:true,  id:"intox_organophos",     name:"Intoxication aux organophosphorés",          def:"Inhibition irréversible de l'acétylcholinestérase. Syndrome muscarinique : bradycardie, bronchospasme, myosis, hypersécrétion, vomissements. Syndrome nicotinique : fasciculations, paralysie musculaire, arrêt respiratoire. Traitement : atropine IV titrée jusqu'à assèchement des bronches, pralidoxime (2-PAM) si précoce (< 6 h), ventilation mécanique." },
  { sys:"Toxicologie", rea:true,  id:"intox_tricycliques",   name:"Intoxication aux antidépresseurs tricycliques", def:"Blocage des canaux sodiques : QRS large > 120 ms → trouble du rythme ventriculaire. Anticholinergique : tachycardie, mydriase, rétention urinaire, hyperthermie. Convulsions, coma. Traitement : bicarbonate de sodium IV bolus si QRS > 120 ms, BZD pour convulsions, éviter antiarythmiques de classe Ic. Surveillance scope 24 h minimum." },
  { sys:"Toxicologie", rea:false, id:"intox_alcool",         name:"Intoxication alcoolique aiguë",              def:"Dépression SNC dose-dépendante. Alcoolémie > 3 g/L : risque coma, hypothermie, inhalation. Traitement : surveillance, protection voies aériennes, réchauffement si hypothermie, glycémie (Wernicke si carencé), hydratation. Sevrage : benzodiazépines titrés (CIWA-Ar). Wernicke : thiamine 500 mg IV avant glucose." },

  /* ===== DERMATOLOGIE GRAVE ===== */
  { sys:"Dermatologie grave", rea:true,  id:"lyell",    name:"Syndrome de Lyell / NET",              def:"Nécrolyse épidermique toxique : décollement > 30 % SCT. SJS < 10 %. Cause médicamenteuse (sulfamides, antiépileptiques, allopurinol). Score SCORTEN pour la mortalité. Prise en charge : unité de brûlés, soins locaux intensifs (pansements non adhérents), arrêt médicament incriminé, antalgiques, nutrition entérale précoce, ciclosporine ou IVIG discutés." },
  { sys:"Dermatologie grave", rea:true,  id:"brulures",  name:"Brûlures étendues graves",            def:"SCT > 20 % adulte. Règle des 9 de Wallace. Profondeur : 2e degré profond + 3e degré. Réanimation Parkland : 4 mL/kg/% SCT/24 h (50 % dans les 8 premières heures). Risque : choc hypovolémique, infection (Pseudomonas, Candida), OAP lésionnel (inhalation). Centre de brûlés si SCT > 15 % ou localisation fonctionnelle." },
  { sys:"Dermatologie grave", rea:false, id:"sjs",       name:"Syndrome de Stevens-Johnson (SJS)",   def:"Éruption bulleuse médicamenteuse touchant < 10 % de la SCT (entre SJS et Lyell : 10–30 % = SJS/NET). Atteinte muqueuse constante (buccale, oculaire, génitale). Gestion identique à NET : arrêt médicament, soins locaux, ophtalmologiste. Pronostic moins sévère que le Lyell, séquelles oculaires possibles." },

  /* ===== PSYCHIATRIE URGENCES ===== */
  { sys:"Psychiatrie urgences", rea:true,  id:"agitation",  name:"Agitation aiguë sévère",           def:"Hyperactivité motrice désorganisée avec agressivité. Éliminer en priorité une cause organique : hypoglycémie, hypoxie, méningite, encéphalopathie, intoxication, sevrage. Sédation si danger : midazolam 5 mg IM ou loxapine 50 mg IM. Contention physique uniquement si danger immédiat, maximum 6 h. Traçabilité obligatoire." },
  { sys:"Psychiatrie urgences", rea:true,  id:"delirium",   name:"Syndrome confusionnel (delirium)",  def:"Confusion aiguë fluctuante avec troubles de l'attention. En réanimation : CAM-ICU. Forme hypoactive (60 %) souvent méconnue. Facteurs de risque : âge, immobilisation, douleur, médicaments anticholinergiques, privation de sommeil. Prévention ABCDEF Bundle. Traitement : réorientation, cycle jour/nuit, mobilisation précoce, halopéridol faible dose si agitation dangereuse." },
  { sys:"Psychiatrie urgences", rea:false, id:"tentative",  name:"Tentative de suicide (TS)",         def:"Urgence médico-psychiatrique. Évaluer gravité somatique d'abord (intoxication, trauma). Score de Columbia pour la létalité. Après stabilisation : évaluation psychiatrique systématique (idéation, planification, facteurs protecteurs). Hospitalisation sous contrainte si risque immédiat (SPDT, SDTU, SDE). Rédiger certificat si nécessaire." },

  /* ===== RHUMATOLOGIE / AUTO-IMMUNITÉ ===== */
  { sys:"Rhumatologie / Auto-immunité", rea:true,  id:"lupus_grave",  name:"Lupus érythémateux systémique (LES) grave", def:"Maladie auto-immune systémique, prévalence féminine. Critères SLICC/ACR. Atteintes graves : néphrite lupique (classe III/IV), pneumopathie lupique, hémorragie alvéolaire, myocardite, thrombopénie sévère, neuropsychiatrique. Traitement : corticoïdes hautes doses, hydroxychloroquine, immunosuppresseurs (mycophénolate, azathioprine), belimumab." },
  { sys:"Rhumatologie / Auto-immunité", rea:false, id:"pra",          name:"Polyarthrite rhumatoïde (PR)",              def:"Arthropathie inflammatoire chronique, facteur rhumatoïde et anti-CCP. Synovite des petites articulations des mains et poignets. Traitement de fond : méthotrexate en 1re ligne, puis anti-TNF (adalimumab, étanercept), JAK-inhibiteurs. Traitement d'une poussée : corticoïdes faible dose. Surveillance : RX mains, DAS28, NFS, transaminases." },
  { sys:"Rhumatologie / Auto-immunité", rea:true,  id:"vascularite",  name:"Vascularites des petits vaisseaux (AAV)",   def:"Granulomatose avec polyangéite (Wegener), polyangéite microscopique, granulomatose éosinophilique (Churg-Strauss). ANCA positifs. Atteintes : pulmonaire (hémorragie alvéolaire = urgence), rénale (GN rapidement progressive), ORL. Traitement : rituximab ou cyclophosphamide + corticoïdes haute dose. Échanges plasmatiques si IRA sévère." },

  /* ===== IMMUNOLOGIE / ALLERGOLOGIE ===== */
  { sys:"Immunologie / Allergologie", rea:true,  id:"anaphylaxie", name:"Choc anaphylactique",                    def:"Réaction allergique systémique sévère IgE-médiée (médicaments, aliments, venin). Urticaire, angiœdème, bronchospasme, hypotension, ACR. Traitement immédiat : adrénaline 0,3 mg IM (cuisse externe) → peut répéter. Si choc : adrénaline IV 50–100 µg bolus, remplissage, corticoïdes + anti-H1 (non urgents). Position allongée jambes levées. EpiPen en sortie." },
  { sys:"Immunologie / Allergologie", rea:false, id:"angioedeme",   name:"Angiœdème bradykinique (HANE)",         def:"Déficit en inhibiteur de C1 esterase → angiœdème non urticarien, résistant aux antihistaminiques et corticoïdes. Localisation : sous-cutanée (mains, pieds, face), abdominale (douleurs), laryngée (urgence vitale). Traitement : icatibant (antagoniste bradykinine), concentré de C1-INH, acide tranexamique. Eviter IEC (facteur déclenchant)." },

];
