// PulseUnit — Pathologies par système avec définitions.
// Expose window.PATHOLOGIES_DATA

window.PATHOLOGIES_DATA = [

  /* ===== CARDIOLOGIE ===== */
  { sys: "Cardiologie", id: "fa", name: "Fibrillation auriculaire (FA)", def: "Arythmie supra-ventriculaire caractérisée par une dépolarisation anarchique des oreillettes à 400–600/min, donnant un rythme ventriculaire irrégulier. Risque principal : AVC embolique. Traitement : anticoagulation, contrôle du rythme ou de la fréquence." },
  { sys: "Cardiologie", id: "idam", name: "Infarctus du myocarde (IDM)", def: "Nécrose ischémique d'une zone myocardique par occlusion d'une artère coronaire. STEMI : sus-décalage ST persistant, revascularisation urgente (< 90 min). NSTEMI : sans sus-décalage, enzymes élevées. Complications : choc cardiogénique, troubles du rythme, IC." },
  { sys: "Cardiologie", id: "ic", name: "Insuffisance cardiaque (IC)", def: "Incapacité du cœur à maintenir un débit suffisant aux besoins métaboliques. IC gauche : dyspnée, OAP. IC droite : œdèmes périphériques, ascite. IC globale : association des deux. Éjection < 40 % = IC à fraction éjectée réduite (ICFEr)." },
  { sys: "Cardiologie", id: "oap", name: "Œdème aigu pulmonaire (OAP)", def: "Extravasation liquidienne dans les alvéoles par élévation de la pression capillaire pulmonaire (cause cardiogénique) ou lésion endothéliale (SDRA). Tableau : orthopnée, crépitants diffus, SpO2 effondrée. Traitement : VNI, diurétiques, vasodilatateurs." },
  { sys: "Cardiologie", id: "choc_card", name: "Choc cardiogénique", def: "État de choc par défaillance primitive de la pompe cardiaque. PAS < 90 mmHg malgré remplissage, IC < 2,2 L/min/m², PAPO > 18 mmHg. Causes : IDM massif, myocardite, valvulopathie aiguë. Traitement : amines, assistance circulatoire (ECMO), revascularisation." },
  { sys: "Cardiologie", id: "tampon", name: "Tamponnade cardiaque", def: "Compression des cavités cardiaques par épanchement péricardique sous tension. Triade de Beck : hypotension, turgescence jugulaire, assourdissement des bruits cardiaques. Urgence : péricardiocentèse ou drainage chirurgical." },
  { sys: "Cardiologie", id: "disseaorte", name: "Dissection aortique", def: "Déchirure de l'intima aortique créant un faux chenal. Type A (crosse) : urgence chirurgicale. Type B (descendante) : traitement médical (contrôle PA, antalgiques). Douleur en coup de poignard irradiant dans le dos." },
  { sys: "Cardiologie", id: "ep", name: "Embolie pulmonaire (EP)", def: "Obstruction des artères pulmonaires par un thrombus (TVP le plus souvent). Gravité : massive (choc), submassive (dysfonction VD sans choc), faible risque. Diagnostic : scanner thoracique. Traitement : anticoagulation, thrombolyse si choc." },
  { sys: "Cardiologie", id: "tvp", name: "Thrombose veineuse profonde (TVP)", def: "Formation d'un thrombus dans le réseau veineux profond, le plus souvent aux membres inférieurs. Facteurs de risque : immobilisation, cancer, chirurgie. Complication principale : embolie pulmonaire. Traitement : anticoagulation (HBPM puis AVK ou AOD)." },
  { sys: "Cardiologie", id: "tach_vent", name: "Tachycardie ventriculaire (TV)", def: "Arythmie à complexes larges, origine ventriculaire, FC > 100/min. TV soutenue (> 30 s) : risque hémodynamique. TV sur cœur sain : pronostic favorable. Traitement : choc électrique si instabilité, amiodarone, ablation à froid." },
  { sys: "Cardiologie", id: "fv", name: "Fibrillation ventriculaire (FV)", def: "Arythmie fatale sans débit cardiaque efficace. Dépolarisation ventriculaire anarchique. Urgence absolue : choc électrique externe immédiat (200 J biphasique), RCP. Cause la plus fréquente d'arrêt cardio-respiratoire." },
  { sys: "Cardiologie", id: "bav3", name: "Bloc auriculo-ventriculaire de degré III", def: "Dissociation complète entre l'activité auriculaire et ventriculaire. Le rythme ventriculaire est assuré par un foyer d'échappement lent (20–40/min). Risque de syncope ou mort subite. Traitement définitif : pacemaker." },

  /* ===== PNEUMOLOGIE / RÉANIMATION RESPIRATOIRE ===== */
  { sys: "Pneumologie / Respiratoire", id: "sdra", name: "Syndrome de détresse respiratoire aiguë (SDRA)", def: "Lésions alvéolaires diffuses d'origine non cardiogénique. Critères Berlin : début < 1 sem., infiltrats bilatéraux, PAPO < 18 mmHg ou absence IC, P/F < 300. Sévérité : léger (200–300), modéré (100–200), sévère (< 100). Ventilation protectrice : VT 6 mL/kg IBW, Pplat < 30." },
  { sys: "Pneumologie / Respiratoire", id: "bpco", name: "BPCO décompensée", def: "Exacerbation de la bronchopneumopathie chronique obstructive. Aggravation aiguë de la dyspnée, augmentation des expectorations ou de leur purulence. Hypoxémie ± hypercapnie. Traitement : bronchodilatateurs, corticostéroïdes, antibiotiques si purulence, VNI si acidose respiratoire." },
  { sys: "Pneumologie / Respiratoire", id: "asthme_grave", name: "Asthme aigu grave", def: "Bronchospasme sévère ne répondant pas au traitement bronchodilatateur initial. SpO2 < 92 %, débit de pointe < 50 % théorique, silence auscultatoire. Urgence vitale : β2 nébulisés, ipratropium, corticoïdes IV, sulfate de magnésium. Intubation si échec." },
  { sys: "Pneumologie / Respiratoire", id: "pneumo_infec", name: "Pneumonie infectieuse", def: "Infection parenchymateuse pulmonaire. Communautaire : pneumocoque, atypiques (Légionella, Mycoplasma). Nosocomiale : Pseudomonas, SARM. Diagnostic : clinique + radiologie. Score CURB-65 pour la gravité. Traitement antibiotique adapté à l'épidémiologie." },
  { sys: "Pneumologie / Respiratoire", id: "pneumo_asp", name: "Pneumonie d'aspiration", def: "Inhalation de contenu gastrique ou de sécrétions oropharyngées dans les voies aériennes. Facteurs de risque : troubles de la déglutition, troubles de la conscience, sonde gastrique. Tableau : fièvre, hypoxémie, infiltrat basithoracique droit. Traitement antibiotique large spectre + anaérobies." },
  { sys: "Pneumologie / Respiratoire", id: "pneumo_vent", name: "Pneumonie sous ventilation mécanique (PAVM)", def: "Pneumonie survenant > 48 h après intubation. Principale complication infectieuse en réanimation. Diagnostic : critères cliniques + LBA. Prévention : position demi-assise 30–45°, soins de bouche chlorhexidine, aspiration sous-glottique. Traitement antibiotique probabiliste puis adapté." },
  { sys: "Pneumologie / Respiratoire", id: "pneumo_hemato", name: "Hémothorax", def: "Épanchement sanguin dans la cavité pleurale. Causes : traumatismes thoraciques, rupture de gros vaisseaux, coagulopathies. Traitement : drainage pleural, parfois chirurgie. Surveillance de l'hémostase et de l'hémodynamique." },
  { sys: "Pneumologie / Respiratoire", id: "pneumo_thorax", name: "Pneumothorax", def: "Présence d'air dans la cavité pleurale. Spontané primaire (homme jeune mince) ou secondaire (BPCO, asthme). Compressif : urgence absolue, déviation trachéale, dégradation hémodynamique. Traitement : exsufflation à l'aiguille puis drainage." },

  /* ===== NEUROLOGIE / NEUROCHIRURGIE ===== */
  { sys: "Neurologie / Neurochirurgie", id: "avc_isch", name: "AVC ischémique", def: "Occlusion artérielle cérébrale entraînant une nécrose par privation d'oxygène. Traitement si < 4h30 : thrombolyse IV (rt-PA) et/ou thrombectomie mécanique si gros vaisseau. NIHSS pour évaluation. Unité neurovasculaire (UNV) obligatoire. Prévention secondaire : antiplaquettaires ou anticoagulants." },
  { sys: "Neurologie / Neurochirurgie", id: "avc_hem", name: "AVC hémorragique", def: "Rupture d'un vaisseau intracrânien avec hématome. Causes : HTA, malformation artério-veineuse, traitement anticoagulant. Contre-indication aux thrombolytiques. Traitement : contrôle tensionnel, reversal des anticoagulants, neurochirurgie si hématome volumineux ou accessible." },
  { sys: "Neurologie / Neurochirurgie", id: "hsd", name: "Hématome sous-dural (HSD)", def: "Collection entre la dure-mère et l'arachnoïde. Aigu (< 3 j) : souvent traumatique, urgence chirurgicale. Chronique (> 3 sem) : progressif, personnes âgées sous anticoagulants. Traitement : selon tolérance clinique, parfois trépanation ou craniotomie." },
  { sys: "Neurologie / Neurochirurgie", id: "hep", name: "Hématome extradural (HED)", def: "Collection entre la dure-mère et la boîte crânienne, souvent par rupture de l'artère méningée moyenne. Intervalle libre classique avant dégradation rapide. Urgence chirurgicale absolue. Bon pronostic si traitement précoce." },
  { sys: "Neurologie / Neurochirurgie", id: "hsa", name: "Hémorragie sous-arachnoïdienne (HSA)", def: "Saignement dans l'espace sous-arachnoïdien, souvent par rupture d'anévrisme. Céphalée foudroyante en coup de tonnerre. Risque de vasospasme (J4–J14), resaignement, hydrocéphalie. Traitement : exclusion anévrismale (clip ou coil), nimodipine, surveillance en réa." },
  { sys: "Neurologie / Neurochirurgie", id: "htc", name: "Hypertension intracrânienne (HTIC)", def: "PIC > 20 mmHg. Causes : œdème cérébral, hématome, hydrocéphalie, tumeur. Triade de Cushing : HTA, bradycardie, bradypnée. Traitement : tête à 30°, osmothérapie (mannitol, sérum salé hypertonique), barbiturates, décompression chirurgicale." },
  { sys: "Neurologie / Neurochirurgie", id: "etat_epi", name: "État de mal épileptique (EME)", def: "Crise épileptique continue > 5 min ou crises répétées sans reprise de conscience. EME convulsif : urgence vitale. Traitement en escalade : BZD IV, antiépileptiques (lévétiracétam, valproate, fosphénytoïne), puis anesthésie générale si réfractaire." },
  { sys: "Neurologie / Neurochirurgie", id: "coma", name: "Coma", def: "Absence de réponse aux stimuli avec yeux fermés. Évaluation GCS. Causes métaboliques (hypoglycémie, intoxications), structurelles (AVC, TC). Prise en charge : protection des voies aériennes, bilan étiologique complet, traitement de la cause." },
  { sys: "Neurologie / Neurochirurgie", id: "mort_cerveau", name: "Mort encéphalique (ME)", def: "Destruction totale et irréversible du cerveau incluant le tronc cérébral. Critères cliniques : absence de conscience, de réflexes du tronc, apnée. Confirmée par 2 EEG iso-électriques ou angioscanner cérébral. Protocole donneur d'organes si état cardio-circulatoire stable." },
  { sys: "Neurologie / Neurochirurgie", id: "tc", name: "Traumatisme crânien (TC)", def: "Lésion cérébrale par impact mécanique. Léger (GCS 13–15), modéré (9–12), grave (≤ 8). Complications : HTIC, hématomes, lésions axonales diffuses. Objectifs en réa : PAM > 80 mmHg, PIC < 20 mmHg, normocapnie, normothermie." },

  /* ===== INFECTIOLOGIE / SEPSIS ===== */
  { sys: "Infectiologie / Sepsis", id: "sepsis", name: "Sepsis", def: "Dysrégulation de la réponse de l'hôte à une infection entraînant une défaillance d'organe. Critères SOFA ≥ 2. Score qSOFA (FR ≥ 22, GCS < 15, PAS ≤ 100) pour dépistage. Traitement : antibiotiques dans l'heure, remplissage, bilan bactériologique préalable." },
  { sys: "Infectiologie / Sepsis", id: "choc_sep", name: "Choc septique", def: "Sepsis avec vasoplégie nécessitant des vasopresseurs pour PAM ≥ 65 mmHg et lactate > 2 mmol/L malgré remplissage adéquat. Mortalité > 40 %. Objectif : noradrénaline en première intention, remplissage prudent, corticothérapie si choc réfractaire (hydrocortisone 200 mg/j)." },
  { sys: "Infectiologie / Sepsis", id: "endocardite", name: "Endocardite infectieuse", def: "Infection de l'endocarde valvulaire ou pariétal. Critères de Duke. Germes : streptocoque, staphylocoque (IV), entérocoque. Complications : emboles septiques, insuffisance valvulaire, abcès annulaire. Antibiothérapie prolongée (4–6 sem), chirurgie si complication." },
  { sys: "Infectiologie / Sepsis", id: "meningite", name: "Méningite bactérienne", def: "Infection des méninges. Triade : fièvre, céphalées, raideur de nuque. Purpura fulminans (méningocoque) = urgence absolue. Ponction lombaire si pas de signe focal. Antibiotiques avant PL si purpura ou instabilité. Céphalosporine 3e génération + corticoïdes IV." },
  { sys: "Infectiologie / Sepsis", id: "fasciite", name: "Fasciite nécrosante", def: "Infection grave des fascias, rapidement extensive. Streptocoque A (type 1) ou polymicrobienne (type 2). Tableau : douleur intense, érythème, nécrose cutanée, choc. Urgence chirurgicale : parage agressif + antibiothérapie large spectre. Mortalité élevée." },
  { sys: "Infectiologie / Sepsis", id: "iatc", name: "Infection sur cathéter", def: "Infection localisée (tunnelite, thrombophlébite) ou systémique (bactériémie) liée à un dispositif veineux. Germes : SCN, S. aureus. Ablation du cathéter en général obligatoire. Antibiothérapie adaptée selon germe et localisation. Prévention : asepsie stricte à la pose et à la manipulation." },
  { sys: "Infectiologie / Sepsis", id: "covid", name: "COVID-19 grave", def: "Infection à SARS-CoV-2 avec détresse respiratoire aiguë. Critères de gravité : SpO2 < 90 %, FR > 30/min, infiltrats > 50 %. Traitement : corticoïdes (dexaméthasone), anticoagulation, antiviraux (remdesivir selon indication). Pronostic : mortalité élevée si ventilation mécanique nécessaire." },
  { sys: "Infectiologie / Sepsis", id: "itu", name: "Infection urinaire sévère (pyélonéphrite/urosepsis)", def: "Infection parenchymateuse rénale ou sepsis d'origine urinaire. Germes : E. coli principalement. Diagnostic : ECBU, hémocultures. Traitement : C3G ou fluoroquinolones IV selon résistances. Durée 10–14 j. Lever l'obstacle si lithiase obstructive." },

  /* ===== HÉPATO-GASTRO-ENTÉROLOGIE ===== */
  { sys: "Hépato-gastro-entérologie", id: "pancreatite", name: "Pancréatite aiguë", def: "Inflammation aiguë du pancréas par auto-digestion. Causes : lithiase, alcool. Score de Ranson ou Balthazar (TDM). Sévère (défaillance d'organe, nécrose) : mortalité élevée. Traitement : remplissage, antalgie, nutrition entérale précoce. Pas d'antibioprophylaxie systématique." },
  { sys: "Hépato-gastro-entérologie", id: "chol_ictere", name: "Cholécystite aiguë", def: "Inflammation aiguë de la vésicule biliaire, souvent sur lithiase. Signe de Murphy, fièvre, douleur de l'hypochondre droit. Complications : gangrène, perforation, cholangite. Traitement : antibiothérapie, cholécystectomie (urgence si compliquée, différée si non compliquée)." },
  { sys: "Hépato-gastro-entérologie", id: "iha", name: "Insuffisance hépatique aiguë (IHA)", def: "Défaillance hépatique sévère chez un patient sans maladie du foie préexistante. Critères : TP < 50 %, encéphalopathie, < 26 sem d'évolution. Causes : paracétamol (N-acétylcystéine), hépatite virale, toxique. Prise en charge : réa spécialisée, évaluation transplantation." },
  { sys: "Hépato-gastro-entérologie", id: "cirrho_deco", name: "Cirrhose décompensée", def: "Complication d'une cirrhose : ascite, encéphalopathie hépatique, hémorragie digestive, infections. Score Child-Pugh ou MELD pour le pronostic. Traitement : spécifique à chaque complication, albumine IV, arrêt alcool, évaluation transplantation." },
  { sys: "Hépato-gastro-entérologie", id: "hd_hte", name: "Hémorragie digestive haute", def: "Saignement au-dessus de l'angle de Treitz. Causes : ulcère gastroduodénal, varices oesophagiennes (cirrhose). Hématémèse ou méléna. Endoscopie dans les 24 h (urgente si choc). Traitement : IPP, octréotide (varices), hémostase endoscopique ou TIPS." },
  { sys: "Hépato-gastro-entérologie", id: "perit", name: "Péritonite", def: "Infection de la cavité péritonéale. Primaire (spontanée sur cirrhose), secondaire (perforation digestive), tertiaire (échec traitement). Tableau : douleur abdominale diffuse, défense/contracture, fièvre, iléus. Traitement : antibiothérapie large spectre + chirurgie urgente si secondaire." },

  /* ===== NÉPHROLOGIE ===== */
  { sys: "Néphrologie", id: "ira", name: "Insuffisance rénale aiguë (IRA)", def: "Élévation brutale de la créatinine ou oligoanurie. Classification KDIGO : stade 1 (créat ×1,5), stade 2 (×2), stade 3 (×3 ou créat > 354 µmol/L ou anurie). Causes : fonctionnelle (hypovolémie), organique (nécrose tubulaire, glomérulonéphrite), obstructive. Traitement : étiologique + épuration extra-rénale si stade 3 symptomatique." },
  { sys: "Néphrologie", id: "eer", name: "Épuration extra-rénale (EER)", def: "Techniques de suppléance rénale. CVVHF/CVVHDF (continu) : préférée en réa pour tolérance hémodynamique. Hémodialyse intermittente : si stable. Indications : hyperhydratation réfractaire, hyperkaliémie > 6,5 mEq/L, acidose sévère, urémie symptomatique." },
  { sys: "Néphrologie", id: "hyperk", name: "Hyperkaliémie sévère", def: "K+ > 6,5 mEq/L ou signes ECG. ECG : ondes T pointues, élargissement QRS, FV. Traitement en urgence : gluconate de calcium IV (protection membranaire), glucose-insuline (transfert K+ intracellulaire), bicarbonates, kayexalate, EER. Surveillance ECG continue." },
  { sys: "Néphrologie", id: "hyponat", name: "Hyponatrémie sévère", def: "Na+ < 125 mEq/L ou symptomatique (convulsions, coma). Causes : dilution (SIADH, potomanie), perte sodée (diurétiques). Correction prudente : max +10 mEq/L/24 h (risque de myélinolyse centropontine). Sérum salé hypertonique si symptomes neurologiques sévères." },

  /* ===== ENDOCRINOLOGIE / MÉTABOLISME ===== */
  { sys: "Endocrinologie / Métabolisme", id: "acd", name: "Acidocétose diabétique (ACD)", def: "Décompensation diabétique avec cétose et acidose (pH < 7,3, bicarbonates < 15, glycémie > 14 mmol/L). Causes déclenchantes : infection, oubli d'insuline. Traitement : remplissage (NaCl 0,9 %), insuline IV, correction K+. Surveillance horaire glycémie et ionogramme." },
  { sys: "Endocrinologie / Métabolisme", id: "hhnc", name: "Hyperosmolarité hyperglycémique (HHNC)", def: "Hyperglycémie > 33 mmol/L, osmolalité > 320 mOsm/kg, sans cétonémie significative. Déshydratation profonde. Patient diabétique type 2 souvent âgé. Traitement : remplissage progressif, insuline à dose modérée, prévention thrombose. Mortalité élevée." },
  { sys: "Endocrinologie / Métabolisme", id: "hypo_gluc", name: "Hypoglycémie sévère", def: "Glycémie < 3 mmol/L avec signes neurologiques ou < 2,5 mmol/L. Causes : insuline, sulfamides, alcool, jeûne. Traitement : glucose 30 % IV ou glucagon IM. Rechercher et corriger la cause. Surveillance prolongée si sulfamides (risque de récidive)." },
  { sys: "Endocrinologie / Métabolisme", id: "thyro_crise", name: "Crise thyréotoxique", def: "Tempête thyroïdienne : hyperthyroïdie extrême avec défaillance multiviscérale. Fièvre > 40°C, tachycardie, agitation, IC, diarrhée. Score de Burch-Wartofsky. Urgence vitale : antithyroïdiens, iode, β-bloquants, corticoïdes, réanimation symptomatique." },
  { sys: "Endocrinologie / Métabolisme", id: "insuf_surr", name: "Insuffisance surrénalienne aiguë", def: "Crise addissonienne : hypotension réfractaire, hypoglycémie, hyponatrémie, hyperkaliémie. Cause : corticothérapie prolongée interrompue, sepsis sur insuffisance latente. Traitement : hydrocortisone 100 mg IV bolus puis 200 mg/24 h, remplissage, glucose." },

  /* ===== TRAUMATOLOGIE / CHIRURGIE ===== */
  { sys: "Traumatologie / Chirurgie", id: "poly_trauma", name: "Polytraumatisme", def: "Au moins deux lésions traumatiques graves dont une met en jeu le pronostic vital. Prise en charge ATLS : Airway, Breathing, Circulation, Disability, Exposure. Contrôle des hémorragies (damage control), prévention de la triade létale : hypothermie + acidose + coagulopathie." },
  { sys: "Traumatologie / Chirurgie", id: "trauma_thor", name: "Traumatisme thoracique grave", def: "Contusion pulmonaire, volet thoracique, pneumo-hémothorax. Volet thoracique : paradoxe ventilatoire, stabilisation si nécessaire. Contusion myocardique : surveillance ECG, enzymes. Rupture aortique : urgence chirurgicale. Scanner corps entier en urgence si mécanisme violent." },
  { sys: "Traumatologie / Chirurgie", id: "trauma_abd", name: "Traumatisme abdominal", def: "Contusion (décélération) ou pénétrant (arme). Organes vulnérables : rate, foie, mésentère. Hémopéritoine : laparotomie d'hémostase si instabilité. Si stable : TDM avec injection. Traitement conservateur possible pour rate et foie si hémostase spontanée." },
  { sys: "Traumatologie / Chirurgie", id: "crush_syndrome", name: "Syndrome de Crush (rhabdomyolyse)", def: "Destruction musculaire massive libérant myoglobine, potassium, CPK. Causes : compression prolongée, polytraumatisme, effort extrême, statines. Risque d'IRA, hyperkaliémie, CID. Traitement : remplissage massif (NaCl 0,9 % ou bicarbonates), diurèse forcée, EER si nécessaire." },

  /* ===== HÉMATOLOGIE / COAGULATION ===== */
  { sys: "Hématologie / Coagulation", id: "cid", name: "Coagulation intravasculaire disséminée (CID)", def: "Activation simultanée et excessive de la coagulation et de la fibrinolyse. Causes : sepsis, polytraumatisme, cancers, complications obstétricales. Tableau : hémorragies diffuses + thromboses. Biologie : TP bas, fibrinogène bas, D-dimères élevés. Traitement : étiologique + transfusion ciblée." },
  { sys: "Hématologie / Coagulation", id: "transfusion", name: "Réaction transfusionnelle grave", def: "Incompatibilité ABO : choc hémolytique aigu, fièvre, douleur lombaire, hémoglobinurie. Arrêt immédiat de la transfusion. TRALI : œdème pulmonaire non cardiogénique dans les 6 h. Allergie anaphylactique : adrénaline. Choc septique sur poche contaminée." },
  { sys: "Hématologie / Coagulation", id: "thrombopenie", name: "Thrombopénie sévère", def: "Plaquettes < 50 G/L. Causes : TIH (thrombopénie induite par l'héparine), PTT, MAT, aplasie. TIH : score 4T, arrêt immédiat héparine, relais anticoagulant non héparinique. PTT : plasmaphérèses en urgence. Risque hémorragique si < 20 G/L." },

  /* ===== OBSTÉTRIQUE ===== */
  { sys: "Obstétrique", id: "eclampsie", name: "Éclampsie", def: "Convulsions généralisées chez une femme prééclamptique. Urgence médicale. Traitement : sulfate de magnésium IV, antihypertenseurs, extraction fœtale urgente. Prévention des récidives par sulfate de magnésium 24 h. Surveillance étroite réflexes ostéotendineux et diurèse." },
  { sys: "Obstétrique", id: "hellp", name: "Syndrome HELLP", def: "Hémolyse, élévation enzymes hépatiques, thrombopénie. Complication sévère de la prééclampsie. Tableau : douleur épigastrique, nausées. Bilan : LDH élevées, ASAT/ALAT élevées, plaquettes < 100 G/L. Traitement : extraction fœtale en urgence, corticoïdes, transfusions si nécessaire." },
  { sys: "Obstétrique", id: "hppi", name: "Hémorragie du post-partum immédiat (HPPI)", def: "Perte sanguine > 500 mL dans les 24 h suivant l'accouchement. Causes : atonie utérine (80 %), rétention placentaire, déchirures, troubles coagulation. Traitement : massage utérin, ocytocine, Sulprostone, sondage vésical, révision utérine, embolisation, chirurgie (ligature, hystérectomie)." },

  /* ===== TOXICOLOGIE ===== */
  { sys: "Toxicologie", id: "intox_paracetamol", name: "Intoxication au paracétamol", def: "Nécrose hépatocellulaire par saturation de la conjugaison (dose > 150 mg/kg). Nomogramme de Rumack-Matthew. Traitement : N-acétylcystéine IV dans les 24 h. Insuffisance hépatique fulminante possible à J3–J4. Critères de King's College pour transplantation hépatique." },
  { sys: "Toxicologie", id: "intox_carbamate", name: "Intoxication aux organophosphorés / carbamates", def: "Inhibition de l'acétylcholinestérase. Syndrome muscarinique (bradycardie, bronchospasme, myosis, hypersalivation) + nicotinique (fasciculations, paralysie). Traitement : atropine IV jusqu'à bronchosécrétion tarie, pralidoxime (organophosphorés uniquement dans les premières heures)." },
  { sys: "Toxicologie", id: "intox_co", name: "Intoxication au monoxyde de carbone (CO)", def: "Hypoxie tissulaire par carboxyhémoglobine (HbCO). Céphalées, nausées, syncope, coma. SpO2 faussement normale (pléthysmographie). Diagnostic : HbCO > 10 % (fumeur) ou 25 % (non-fumeur). Traitement : O2 100 % masque haute concentration, oxygénothérapie hyperbare si grave." },
  { sys: "Toxicologie", id: "intox_tricycliques", name: "Intoxication aux antidépresseurs tricycliques", def: "Blocage des canaux sodiques : QRS large, QT long, tachycardie. Effet anticholinergique : mydriase, rétention urinaire, iléus, hyperthermie. Convulsions, coma. Traitement : bicarbonate de sodium IV si QRS > 120 ms, benzodiazépines pour convulsions. Pas de flumazénil." },

  /* ===== DERMATOLOGIE GRAVE ===== */
  { sys: "Dermatologie grave", id: "lyell", name: "Syndrome de Lyell (NET)", def: "Nécrolyse épidermique toxique : décollement épidermique > 30 % de la surface corporelle. Cause : médicaments (sulfonamides, antiépileptiques, allopurinol). Score SCORTEN pour pronostic. Traitement : arrêt médicament incriminé, soins locaux intensifs, unité de brûlés ou réanimation. Mortalité 30–40 %." },
  { sys: "Dermatologie grave", id: "brulures", name: "Brûlures étendues graves", def: "SCT > 20 % (adulte) ou > 10 % (enfant). Règle des 9 de Wallace. Profondeur : 1er (rouge), 2e (phlyctène), 3e (escarre). Réanimation : Parkland = 4 mL/kg/% SCT/24 h. Risque : choc hypovolémique, infection, insuffisance respiratoire (inhalation). Prise en charge en centre de brûlés." },

  /* ===== PSYCHIATRIE URGENCES ===== */
  { sys: "Psychiatrie urgences", id: "agitation", name: "Agitation aiguë", def: "Activité motrice excessive désorganisée avec agressivité. Causes organiques à éliminer en premier : hypoglycémie, hypoxie, méningite, intoxication. Si origine psychiatrique : neuroleptiques sédatifs (halopéridol, loxapine), benzodiazépines. Contention physique en dernier recours." },
  { sys: "Psychiatrie urgences", id: "delirium", name: "Syndrome confusionnel (delirium)", def: "Confusion mentale aiguë avec fluctuations. En réanimation : évaluation CAM-ICU. Facteurs de risque : âge, immobilisation, douleur, sevrage, médicaments. Prévention : réveil quotidien, réorientation, cycles jour/nuit, mobilisation précoce. Traitement : halopéridol faible dose si hyperactif et dangereux." },

];
